=== Haru-jzmPRG/LMSGI/catalogo.dtd
<!ELEMENT catalog (book+)>

<!ELEMENT book (dc:title, dc:creator, dc:date)>
<!ATTLIST book id ID #REQUIRED>

<!ELEMENT dc:title (#PCDATA)>
<!ELEMENT dc:creator (#PCDATA)>
<!ELEMENT dc:date (#PCDATA)>

=== Haru-jzmPRG/LMSGI/caltalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoteca SYSTEM "catalogo.dtd">

<catalog>
    <book id="bk-001">
        <dc:title>Té-ología de la Abuela</dc:title>
        <dc:creator>Roger Gutiérrez</dc:creator>
        <dc:date>2024</dc:date>
    </book>

    <book id="bk-002">
        <dc:title>Tea History Coloring Book</dc:title>
        <dc:creator>Aurea Studio</dc:creator>
        <dc:date>2025</dc:date>
    </book>

    <book id="bk-003">
        <dc:title>Weekly Tea Wellness Planner</dc:title>
        <dc:creator>Aurea Publishing</dc:creator>
        <dc:date>2025</dc:date>
    </book>

</catalog>
